# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - lint
  - test
  - push

image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
  GL_ASDF_TFLINT_VERSION: $TFLINT_VERSION
  GL_ASDF_TERRAFORM_VERSION: $TERRAFORM_VERSION
  # Exclude vendor and files directories from validation
  COMMON_TASK_VALIDATIONS_EXCLUDES_REGEXP: '^\.(/vendor/|/files/)'


include:
  - template: Security/SAST.gitlab-ci.yml
  # Runs tflint on all terraform module directories
  # see https://gitlab.com/gitlab-com/gl-infra/common-ci-tasks/-/blob/main/tflint.md
  - remote: 'https://gitlab.com/gitlab-com/gl-infra/common-ci-tasks/-/raw/v1.78.1/tflint.yml'
  - remote: 'https://gitlab.com/gitlab-com/gl-infra/common-ci-tasks/-/raw/v1.78.1/.gitlab-ci-asdf-versions.yml'
  - project: 'platformengineering/tf-module-ci'
    ref: main
    file: '.gitlab-ci.yml'

terraform_check:
  stage: lint
  script:
    - terraform fmt -check -recursive .

tflint:
  stage: lint
  before_script:
    - echo -e "credentials \"git.oxolo.com\" {\n  token = \"$CI_JOB_TOKEN\"\n}" > /root/.terraformrc
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - if: $CI_PIPELINE_SOURCE == 'schedule'
      when: never
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      allow_failure: false

sast:
  stage: test

upload-module:
  stage: push
  before_script:
    - echo "uploading module to infrastructure registry"
