# DO NOT MANUALLY EDIT; Run ./scripts/update-asdf-version-variables.sh to update this
variables:
    GL_ASDF_GOLANG_VERSION: 1.19.2
    GL_ASDF_GORELEASER_VERSION: 1.13.1
    GL_ASDF_JB_VERSION: 0.5.1
    GL_ASDF_JSONNET_TOOL_VERSION: 1.7.0
    GL_ASDF_PRE_COMMIT_VERSION: 2.21.0
    GL_ASDF_SHELLCHECK_VERSION: 0.9.0
    GL_ASDF_SHFMT_VERSION: 3.6.0
    GL_ASDF_YQ_VERSION: 4.30.6
